models:
  knn:
    enabled: true
    params:
      n_neighbors: [3, 5, 7, 9]
      weights: ['uniform', 'distance']
      metric: ['euclidean', 'manhattan']
  xgboost:
    enabled: true
    params:
      max_depth: [3, 5, 7]
      learning_rate: [0.01, 0.1]
      n_estimators: [100, 200]
  lightgbm:
    enabled: true
    params:
      num_leaves: [31, 127]
      learning_rate: [0.01, 0.1]
      n_estimators: [100, 200]

features:
  technical_indicators:
    - RSI
    - MACD
    - Bollinger_Bands
    - Stochastic_Oscillator
    - ATR
    - OBV
    - ADX
    - CCI
  time_features:
    - Day_of_Week
    - Month
    - Quarter
    - Is_Weekend

prediction_horizons:
  - 1  # 1 day
  - 7  # 1 week
  - 30 # 1 month

alerts:
  price_change:
    threshold: 5.0  # Percentage
    enabled: true
  volume_spike:
    threshold: 200.0  # Percentage
    enabled: true
  trend_reversal:
    enabled: true

backtesting:
  enabled: true
  test_size: 0.2
  windows: [30, 90, 180]  # Days

email_notifications:
  enabled: false
  smtp_server: ""
  smtp_port: 587
  sender_email: ""
